# Changes here will be overwritten by Copier
_commit: 99f787e
_src_path: ../caldata-infrastructure-template/
dbt_profile_name: sample_project
email_address: test@test.com
friendly_project_name: Sample Project
license: MIT
project_name: sample-project-Snowflake
team_name: Test team
